#!/usr/bin/env bash
# Define the file name for the key pair
KEY_NAME="school"
# Define the passphrase
PASSPHRASE="betty"
# Generate the RSA key pair with 4096 bits and the specified passphrase
ssh-keygen -t rsa -b 4096 -f $KEY_NAME -N "$PASSPHRASE"
# Output success message and list files in the directory
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $KEY_NAME."
echo "Your public key has been saved in $KEY_NAME.pub."
echo "The key fingerprint is:"
ssh-keygen -lf $KEY_NAME
echo "The key's randomart image is:"
ssh-keygen -lvf $KEY_NAME | grep -v '^$'
ls -l $KEY_NAME $KEY_NAME.pub
